apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-clusters
data:
  cluster1: |
    {
      "tier": "dev",
      "provider": "aws",
      "region": "us-west-2",
      "cluster": "cluster1"
    }

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wasmcloud-host
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wasmcloud-host
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wasmcloud-host
subjects:
  - kind: ServiceAccount
    name: "wasmcloud-host"
    namespace: "default"