apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: clusters
  annotations:
    version: v0.0.2
    description: 'clusters application'
    wasmcloud.dev/authors: cloud-platform team
spec:
  components:
    - name: kv-kube-cfgmaps
      type: capability
      properties:
        image: kind-registry:5000/kube-cfgmaps:v0.0.16
        id: kv-kube-cfgmaps
        config:
          - name: provider-config
            properties:
              team: cloud-platform
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: link
          properties:
            target: clusters-info
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8000
    - name: clusters-info
      type: component
      properties:
        image: kind-registry:5000/clusters-info:v0.0.10
        id:  clusters-info
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: kv-kube-cfgmaps
            namespace: wrpc
            package: keyvalue
            interfaces: [store]