apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: clusters
  annotations:
    version: v0.0.1
    description: 'clusters application'
    wasmcloud.dev/authors: cloud-platform team
spec:
  components:
    - name: kv-kube-cfgmaps
      type: capability
      properties:
        image: localhost:5000/kube-cfgmaps:v0.0.1
        id: kv-kube-cfgmaps
        config:
          - name: provider-config
            properties:
              team: cloud-platform
    - name: clusters-info
      type: component
      properties:
        image: localhost:5000/clusters-info:v0.0.1
        id: clusters-info
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: kv-kube-cfgmaps
            namespace: wrpc
            package: keyvalue
            interfaces: [store]