package cloud-platform:clusters;

interface cluster-api {

  variant error {
    cluster-not-found,

    other(string)
  }
  
  record data {
    tier: string,
    provider: string,
    region: string,
    cluster: string,
  }

  get-cluster-info: func() ->  result<data, error>;
}

world clusters {
  export cluster-api;
  import wrpc:keyvalue/store@0.2.0-draft;
  include wasmcloud:component-go/imports@0.1.0;
}
